[cmake]
version = "3.15"
cmkr-include = "cmake/cmkr.cmake"

[project]
name = "UnknownKit"
version = "0.1.0"
description = "UnknownKit"
include-after = ["cmake/Qt5Helpers.cmake"]
msvc-runtime = "static"

[find-package]
Qt6 = { components = ["Widgets", "Core5Compat"] }

[target.UnknownKit]
type = "executable"
sources = [
    "UnknownKit/main.cpp",
    "UnknownKit/MainWindow.cpp",
    "UnknownKit/MainWindow.h",
    "UnknownKit/MainWindow.ui",
    "UnknownKit/resource.qrc",
]
link-libraries = ["Qt6::Widgets", "Qt6::Core5Compat"]
msvc.link-options = ["/SUBSYSTEM:WINDOWS"]
cmake-after = """
# Enable Qt moc/rrc/uic support
target_qt(${CMKR_TARGET})
"""

[[install]]
targets = ["UnknownKit"]
destination = "bin"
